"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./Components/Header";
import { Footer } from "./Components/Footer";
import { createContext, useContext, useState } from "react";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: 'Blog',
//   description: 'Generated by create next app',
// }
export const SearchContext = createContext();



export default function RootLayout({ children }) {
  const [search,setSearch]=useState('');
  const [hide,setHide]=useState(true);
  const hideMenu=()=>{
  
  }
  return (
    <html lang="en">
      <body className={`${inter.className} m-auto flex flex-col`}>
        <SearchContext.Provider value={{ search, setSearch, hide, setHide }}>
          <Header />
          {children}
          <Footer />
        </SearchContext.Provider>
      </body>
    </html>
  );
}
export const useSearch = () => useContext(SearchContext);
